services:
  backend:
    build: .
    restart: always
    container_name: picky-be
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - mongo
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?allowLoadLocalInfile=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/${MONGO_DATABASE}?authSource=admin
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
      GOOGLE_OAUTH_BASE_URL: ${GOOGLE_OAUTH_BASE_URL}
      CHROME_EXTENSION_GOOGLE_CLIENT_ID: ${CHROME_EXTENSION_GOOGLE_CLIENT_ID}
      JWT_SECRET: ${JWT_SECRET}
      APP_SEED_CSV_PATH: ${APP_SEED_CSV_PATH:-/app/data/quiz_wiki_all.csv}
      APP_FACT_SEED_CSV_PATH: /app/data/facts.csv
      APP_COOKIE_NAME: ${APP_COOKIE_NAME}
      APP_COOKIE_DOMAIN: ${APP_COOKIE_DOMAIN}
      APP_COOKIE_PATH: ${APP_COOKIE_PATH}
      APP_COOKIE_HTTP_ONLY: ${APP_COOKIE_HTTP_ONLY}
      APP_COOKIE_SECURE: ${APP_COOKIE_SECURE}
      APP_COOKIE_SAME_SITE: ${APP_COOKIE_SAME_SITE}
      APP_COOKIE_MAX_AGE: ${APP_COOKIE_MAX_AGE}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      MONGO_BROWSING_COLLECTION: ${MONGO_BROWSING_COLLECTION}
    networks:
      - picky-network
    volumes:
      - ${HOST_DATA_DIR:-./data}:/app/data

  db:
    image: mysql:8.0
    container_name: picky-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - --local-infile=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --default-time-zone=+09:00
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - picky-network

  redis:
    image: redis:7
    container_name: picky-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - picky-network

  mongo:
    image: mongo:6
    container_name: picky-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - picky-network

volumes:
  db_data:
  mongo_data:

networks:
  picky-network:
    external: true
